# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    tags: [ "release/*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        pdm install
    - name: Build exe
      run: |
        $env:PATH = "C:\msys64\usr\bin;$env:PATH"
        pdm build_exe --assume-yes-for-downloads
    - name: Add build data
      run: git show --no-patch > Convert2EBRL.dist/build-data.txt
    - name: add-release-hash
      if: github.ref_type == 'tag'
      run: python "src\convert2ebrl\hash_utils.py" "Convert2EBRL.dist\Convert2EBRL.exe" > "Convert2EBRL\release.hash"
    - name: Create release zip
      run: Compress-Archive -Path Convert2EBRL.dist -Destination convert2ebrl-continuous.zip
    - name: Update continuous tag
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.updateRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'tags/continuous',
            sha: context.sha
          })
    - name: Update continuous release
      uses: softprops/action-gh-release@v2
      with:
        name: continuous
        tag_name: continuous
        files: convert2ebrl-continuous.zip
        prerelease: true
        draft: false
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: convert2ebrl-dist
        path: Convert2EBRL.dist
